baseURL = "https://openmedgate.com/"
languageCode = "en"
title = "OpenMedGate"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Hugo modules
enableRobotsTXT = true
enableGitInfo = true

# Build settings
[minify]
  minifyOutput = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]

[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "720h"
