author = "OpenMedGate"
description = "Open infrastructure for healthcare AI interoperability"

ogImage = "/images/og-image.png"
twitterHandle = "@openmedgate"

quantummedURL = "https://quantummed.eu"
medicoaiURL = "https://medicoai.eu"

hubspotPortalId = "146629432"
hubspotFormId = "aeadca76-4128-4c72-a7c6-260b461c8a75"
newsletterFormGuid = "e4bcb230-3e96-439e-b9bb-7fc0a40974ff"


countdownEnabled = true
countdownTargetDate = "2026-08-01T00:00:00Z"

cookieConsentEnabled = true

darkModeEnabled = true
darkModeDefault = "dark"

[nav]
  logo = "/images/logo2.png"

[footer]
  copyright = "OpenMedGate"
